### ISSUE TITLE
Upstream rust package does not build

### ISSUE THREAD

**Issue by arvl130** [arvl130/kiss32-repo#2]
The upstream [rust](https://github.com/kisslinux/repo/tree/master/extra/rust) package currently requires pre-compiled binaries from [rust-lang.org](https://rust-lang.org/) in order to build.

[At the time of writing](https://static.rust-lang.org/dist/2020-06-04/), rust-lang.org does not provide binaries for i686 Musl rustc and cargo, so we cannot currently build Rust and Rust-dependent packages on the distro.

**Comment by motorto** [comment]
Maybe upstream can remove those pre-compiled binaries or we could make a new rust package ... 

I know that kiss only focus on x86 cpus but maybe opening an issue there might make something

**Comment by arvl130** [comment]
I'm not sure if we can ask upstream to stop using those binaries. They are kind of required to build rust.

`rustc` can only be built with `rustc` (and I think other parts of the package as well) so we'll have to figure out a way to get our own bootstrapping `rustc` binary if we want to get this package building.

I've thought we might be able to just use Alpine's own binaries -- they use Musl as well, and they have x86 binaries. However, needless to say, this will be an ugly hack.

If not that, there is a re-implementation of rustc made in C++ (See: [mrustc](https://github.com/thepowersgang/mrustc)). We might be able to use it as a boostrapper. I have not done any sort of testing on it though, I've only found it just now.
